version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py

  frontend:
    build: ./frontend
    ports:
      - "8097:80"
